# Set Hadoop-related environment variables
# !! WARNING - Ensure this matches your install

export HADOOP_HOME=/usr/lib/hadoop
export HADOOP_VERSION=1.0.2
export HADOOP_CONF_DIR=/etc/hadoop/conf

export LD_PRELOAD=/lib/i386-linux-gnu/libssl.so.1.0.0

# Set JAVA_HOME (we will also configure JAVA_HOME directly for Hadoop later on)`
# !! WARNING - Ensure this matches your install

export JAVA_HOME=/usr/lib/jvm/java-1.6.0-openjdk
export BOOST_PYTHON=boost_python-2.7

# Some convenient aliases and functions for running Hadoop-related commands

unalias fs &> /dev/null
alias fs="hadoop fs"
unalias hls &> /dev/null
alias hls="fs -ls"

# Add Hadoop bin/ directory to PATH

export PATH=$PATH:$HADOOP_HOME/bin
