# Set Hadoop-related environment variables
# !! WARNING - Ensure this matches your install

export HADOOP_HOME=/etc/hadoop

# Set JAVA_HOME (we will also configure JAVA_HOME directly for Hadoop later on)`
# !! WARNING - Ensure this matches your install

export JAVA_HOME=/usr/lib/jvm/java-1.6.0-openjdk

# Some convenient aliases and functions for running Hadoop-related commands

unalias fs &> /dev/null
alias fs="hadoop fs"
unalias hls &> /dev/null
alias hls="fs -ls"

# Add Hadoop bin/ directory to PATH

export PATH=$PATH:$HADOOP_HOME/bin